In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd

In [3]:
user_data=pd.read_csv('user_data.csv')
user_data.head()

   user_id  item_id  rating  timestamp
0        0       50       5  881250949
1        0      172       5  881250949
2        0      133       1  881250949
3      196      242       3  881250949
4      186      302       3  891717742

In [5]:
movies=pd.read_csv('Movie_Id_Titles.csv')
movies.head()

   item_id              title
0        1   Toy Story (1995)
1        2   GoldenEye (1995)
2        3  Four Rooms (1995)
3        4  Get Shorty (1995)
4        5     Copycat (1995)

In [6]:
df=pd.merge(user_data,movies, on='item_id')

In [7]:
df.head()

   user_id  item_id  rating  timestamp                            title
0        0       50       5  881250949                 Star Wars (1977)
1        0      172       5  881250949  Empire Strikes Back, The (1980)
2        0      133       1  881250949        Gone with the Wind (1939)
3      196      242       3  881250949                     Kolya (1996)
4      186      302       3  891717742         L.A. Confidential (1997)

In [8]:
movie_matrix=df.pivot_table(index='user_id', columns='title', values='rating')
movie_matrix

title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Yankee Zulu (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
user_id,,,,,,,,,,,,,,,,,,,,,
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,2.0,5.0,NaN,NaN,3.0,4.0,NaN,NaN,...,NaN,NaN,NaN,5.0,3.0,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
940,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
943,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4.0,3.0,NaN,NaN,NaN,NaN

In [9]:
movie_matrix.to_csv('movie_matrix.csv')

In [12]:
startwars_ratings = movie_matrix['Star Wars (1977)']
startwars_ratings

user_id
0      5.0
1      5.0
2      5.0
3      NaN
4      5.0
      ...
939    NaN
940    4.0
941    NaN
942    5.0
943    4.0
Name: Star Wars (1977), Length: 944, dtype: float64

In [17]:
similar_to_starwars = movie_matrix.corrwith(startwars_ratings).sort_values(ascending=False)
similar_to_starwars

title
Hollow Reed (1996)                         1.0
Commandments (1997)                        1.0
Cosi (1996)                                1.0
No Escape (1994)                           1.0
Stripes (1981)                             1.0
                                          ...
Wonderland (1997)                          NaN
Wooden Man's Bride, The (Wu Kui) (1994)    NaN
Yankee Zulu (1994)                         NaN
You So Crazy (1994)                        NaN
Á köldum klaka (Cold Fever) (1994)         NaN
Length: 1664, dtype: float64

In [18]:
corr_starwars=pd.DataFrame(similar_to_starwars, columns=['Correlation'])

In [21]:
corr_starwars.dropna(inplace=True)

In [22]:
corr_starwars

                            Correlation
title
Hollow Reed (1996)                  1.0
Commandments (1997)                 1.0
Cosi (1996)                         1.0
No Escape (1994)                    1.0
Stripes (1981)                      1.0
...                                 ...
For Ever Mozart (1996)             -1.0
Frankie Starlight (1995)           -1.0
I Like It Like That (1994)         -1.0
American Dream (1990)              -1.0
Theodore Rex (1995)                -1.0

[1410 rows x 1 columns]

In [39]:
ratings = pd.DataFrame(df.groupby('title')['rating'].count())

In [40]:
ratings

                                       rating
title
'Til There Was You (1997)                   9
1-900 (1994)                                5
101 Dalmatians (1996)                     109
12 Angry Men (1957)                       125
187 (1997)                                 41
...                                       ...
Young Guns II (1990)                       44
Young Poisoner's Handbook, The (1995)      41
Zeus and Roxanne (1997)                     6
unknown                                     9
Á köldum klaka (Cold Fever) (1994)          1

[1664 rows x 1 columns]

In [41]:
corr_starwars=corr_starwars.join(ratings['rating'])
corr_starwars

                            Correlation  rating
title
Hollow Reed (1996)                  1.0       6
Commandments (1997)                 1.0       3
Cosi (1996)                         1.0       4
No Escape (1994)                    1.0       5
Stripes (1981)                      1.0       5
...                                 ...     ...
For Ever Mozart (1996)             -1.0       3
Frankie Starlight (1995)           -1.0       4
I Like It Like That (1994)         -1.0       3
American Dream (1990)              -1.0       2
Theodore Rex (1995)                -1.0       5

[1410 rows x 2 columns]

In [42]:
corr_starwars[corr_starwars['rating']>100]

                                                    Correlation  rating
title
Star Wars (1977)                                       1.000000     584
Empire Strikes Back, The (1980)                        0.748353     368
Return of the Jedi (1983)                              0.672556     507
Raiders of the Lost Ark (1981)                         0.536117     420
Austin Powers: International Man of Mystery (1997)     0.377433     130
...                                                         ...     ...
Edge, The (1997)                                      -0.127167     113
As Good As It Gets (1997)                             -0.130466     112
Crash (1996)                                          -0.148507     128
G.I. Jane (1997)                                      -0.176734     175
First Wives Club, The (1996)                          -0.194496     160

[334 rows x 2 columns]

In [44]:
liarliar_ratings = movie_matrix['Liar Liar (1997)']
similar_to_liarliar = movie_matrix.corrwith(liarliar_ratings).sort_values(ascending=False)
corr_liarliar=pd.DataFrame(similar_to_liarliar, columns=['Correlation'])
corr_liarliar.dropna(inplace=True)
corr_liarliar=corr_liarliar.join(ratings['rating'])
corr_liarliar[corr_liarliar['rating']>100]

                                                    Correlation  rating
title
Liar Liar (1997)                                       1.000000     485
Batman Forever (1995)                                  0.516968     114
Mask, The (1994)                                       0.484650     129
Down Periscope (1996)                                  0.472681     101
Con Air (1997)                                         0.469828     137
...                                                         ...     ...
Hoop Dreams (1994)                                    -0.184503     117
Ed Wood (1994)                                        -0.199481     133
Dr. Strangelove or: How I Learned to Stop Worry...    -0.238092     194
Welcome to the Dollhouse (1995)                       -0.254231     112
Raging Bull (1980)                                    -0.308129     116

[334 rows x 2 columns]

In [45]:
RB_ratings = movie_matrix['Raging Bull (1980)']
similar_to_RB = movie_matrix.corrwith(RB_ratings).sort_values(ascending=False)
corr_RB=pd.DataFrame(similar_to_RB, columns=['Correlation'])
corr_RB.dropna(inplace=True)
corr_RB=corr_RB.join(ratings['rating'])
corr_RB[corr_RB['rating']>100]

                                     Correlation  rating
title
Raging Bull (1980)                      1.000000     116
Ice Storm, The (1997)                   0.671332     108
Fly Away Home (1996)                    0.550564     180
Ed Wood (1994)                          0.519802     133
Devil's Advocate, The (1997)            0.506370     188
...                                          ...     ...
Bram Stoker's Dracula (1992)           -0.390554     120
Peacemaker, The (1997)                 -0.410004     136
Mr. Smith Goes to Washington (1939)    -0.429679     105
Down Periscope (1996)                  -0.522958     101
Scream 2 (1997)                        -0.570088     106

[334 rows x 2 columns]

In [ ]:
RB_ratings = movie_matrix['Raging Bull (1980)']
similar_to_RB = movie_matrix.corrwith(RB_ratings).sort_values(ascending=False)
corr_RB=pd.DataFrame(similar_to_RB, columns=['Correlation'])
corr_RB.dropna(inplace=True)
corr_RB=corr_RB.join(ratings['rating'])
corr_RB[corr_RB['rating']>100]